### ISSUE TITLE
Not working on Python3 and Ubuntu 20

### ISSUE THREAD

**Issue by kaitcoa** [aerospike-community/aerospike-collectd#18]
Hello there, I was unable to make it running on Ubuntu 20 LTS with python3 installed and all necessary modules. 
With python2 and pip build fails, and the first thing I had to do is to change to aerospike-client version to 4.0 in requirements.txt, and additionally, I had to fix importing of ServerError exception inside of aerospike_plugin.py. 
However, I am still unable to run it successfully. Could you please help somehow?

Here is the last log.
[aerospike_log.txt](https://github.com/aerospike-community/aerospike-collectd/files/5498030/aerospike_log.txt)

**Comment by asaf400** [comment]
@kaitcoa Yeah, I'm the one who Added 'ServerError' import for aerospike,
at the time (a month ago), the latest aerospike client had this module, now it doesn't:
ModuleNotFoundError: No module named 'aerospike.exception'; 'aerospike' is not a package

I have found the issue, and have opened a PR: https://github.com/aerospike-community/aerospike-collectd/pull/19
however I still see that python3 is used in master, but collectd module doesn't support it:
  File "/usr/local/lib/python3.7/site-packages/collectd.py", line 8, in <module>
    from Queue import Queue, Empty
ModuleNotFoundError: No module named 'Queue'

https://github.com/appliedsec/collectd/issues/7

**Comment by asaf400** [comment]
I updated the PR to use the python3 support feature branch in requirements.txt,
if you try to run the .py file as is, it will fail with:

> Traceback (most recent call last):
> 
>   File "/opt/collectd-plugins/aerospike_plugin.py", line 960, in <module>
>     collectd.register_init(plugin.init)
> AttributeError: 'module' object has no attribute 'register_init'

however, running under collectd as a plugin works fine, and metrics are emitted

**Comment by kaitcoa** [comment]
@asaf400 Thanks!

**Comment by asaf400** [comment]
Jumping in here from the future, 
although we didn't get this repo to work with changes in Aerospike 5.7.0.9* and the latest python aerospike module,
Me and my coworkers managed to get collectd to run python3 explicitly, 
so for anyone who'll find this useful, here's how to do it:

First clone the collectd repo: https://github.com/collectd/collectd
Then make sure you install some of the pre-requisites for compiling C \ CPP, which mainly include:
autoconf, pkg-config, bison and:
- `yum groupinstall "Development tools"` for RHEL\Fedora based
- `apt-get install build-essential` for Debian based

After that make sure to install: python3-devel (RHEL) or python3-dev (Deb)
and then `cd` into the collectd repo root, and just run `autoconf`
you'll see that the ./configure script has been created\updated (timestamp), you can now run it with `--enable-python` flag, so:
`./configure --enable-python`
then you may inspect the Makefile, and make sure python3 libs are loaded (look for python \ python3 references in the Makefile)
After that run `make install` or `make install all` and now, collectd should load python3 when using the python module

can be verified with the following snippet, simply placed somewhere.. ( start of aerospike_plugin.py for example )
```python
import sys
collectd.info("Python version: %s" % sys.version)
```

What happened?
Running `autoconf` after python3-dev(el) is installed, allows autoconf & confiure.ac scripts to detect python installation based on version priority, as I guess is [written here](https://github.com/collectd/collectd/blob/a4d005779bd3d67a2006d7286d4d07bb9dac1bc7/configure.ac#L4951), if python3-config binary exists (installed by dev package), it would use that, else it would fallback to the older versions..

* Last known version to work for me is aerospike 5.2, 
I don't know at which point this repo became incompatible.
